# Generated by Django 3.0.7 on 2020-06-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
